#!/usr/bin/env perl

use warnings;
use strict;

use Google::Apps;

@ARGV == 3 or print "usage: $0 domain username password\n" and exit -1;

my $apps = Google::Apps->new(
    domain   => $ARGV[0],
    username => $ARGV[1],
    password => $ARGV[2],
);

my $r = $apps->get_reporting_api;

my $csv = $r->report_csv(name => "accounts", date => "2009-10-25", page => 1);
print $csv;
